### PR TITLE
changed decrypted API call with new ones

### PR DESCRIPTION
**Pull request by mdrummerboy09**
[Tracker Story](https://www.pivotaltracker.com/story/show/177855214)

Slack decrypted some API calls. changed groups.invite to conversations.invite

### CODE REVIEW

**Comment by dynamike** [comment]
Defer to @duncan-truss on approve/reject. Generally seems okay to me.

**Comment by duncan-truss** [comment]
@mdrummerboy09 I think the code changes looks sufficient.  From reading the docs we likely need to update the oauth scopes of the Slack App to match what is required of the `conversations.invite` method.

Required api scopes
Screen Shot 2021-04-21 at 2 42 52 PM

Existing api scopes of Slack App
Screen Shot 2021-04-21 at 2 43 11 PM

Let me know if you can't access the Slack App settings here https://api.slack.com/apps/AL1P10V45/oauth

**Comment by mdrummerboy09** [comment]
@duncan-truss I don't think I am able to change/add scopes to this slack app

**Comment by duncan-truss** [comment]
> @duncan-truss I don't think I am able to change/add scopes to this slack app

Added you as a collaborator.

**Comment by mdrummerboy09** [comment]
awesome scopes have been updated and good to go now.

**Review by duncan-truss — APPROVED** [review]
The user token scopes look good, it might be worth revisiting all the bot token scopes since it seemed to add extra on upgrade.

**Pull request merged**
